exclude: 'docs/|agentfly/verl/|verl/|tests/'

repos:
  # 1. General Sanity Checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace      # Removes unnecessary spaces at ends of lines
      - id: end-of-file-fixer        # Ensures files end with a newline
      - id: check-yaml               # Validates your YAML files
      - id: check-added-large-files  # Prevents accidentally committing giant files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.13
    hooks:
      - id: ruff
        args: [ --fix ]             # Automatically fix linting errors
      - id: ruff-format             # Formats the code like Black

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["src"]
